### ISSUE TITLE
IDE doesn't recognize the .zip for including

### ISSUE THREAD

**Issue by DavidC284** [sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library#20] opened 2023-11-27 04:58 UTC
### Subject of the issue
I feel stupid for asking, but I did a download from this site to my Download directory.   Then tried to have the IDE add it as a library, but it replied 'Specified folder/zip file does not contain a valid library'.       What did I do wrong or need to do to fix this?

Using IDE 1.8.16.

Thanks,
Dave

### Your workbench
* What development board or microcontroller are you using?
* What version of hardware or breakout board are you using? 
* How is the breakout board wired to your microcontroller?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by sfe-SparkFro** [comment] 2023-11-27 16:57
Hi there, sorry to hear you're having trouble! I tried to replicate this, but it works fine on my end, so I can't say for certain what the problem is on your end.

Where exactly did you download the zip file from? This GitHub repo, or somewhere else? And which branch did you download, `main` or `master`? Looks like `master` is an older version, `main` is the latest.

How exactly are you adding it as a library? I assume you're doing "Sketch -> Include Library -> Add .ZIP Library..." is that correct? Could you instead install it from the Arduino Library Manger? "Sketch -> Include Library -> Manage Libraries..." then search for "SparkFun Qwiic Alphanumeric Display Arduino Library"

One other quick comment - you're on version 1.8.X of the IDE, which is the legacy version and about 2 years out of date at this point. I'd really suggest using the latest version of Arduino IDE 2, which you can download from here: https://www.arduino.cc/en/software

Given that I'm unable to replicate on the latest version of the IDE, I don't think this is an issue with this library, so I'm going to close this issue for now. If you're still having trouble, please feel free to reply here or on [our support forum](https://forum.sparkfun.com/) for more assistance! Or if you truly believe the root problem is with this library, then please reopen this issue with more details about what you think the exact problem is.

Hope this helps!

**Closed by sfe-SparkFro** 2023-11-27 16:57 UTC
