### ISSUE TITLE
Confused on Defining the I2C to the Nano

### ISSUE THREAD

**Issue by DavidC284** [sparkfun/SparkFun_Alphanumeric_Display_Arduino_Library#21] opened 2023-11-29 20:59 UTC
This really isn't an issue with either the HW or the library...yet ...

I'm still trying to get the Nano to talk to the VK16k33.   The Nano has two dedicated pins for the I2C channel, pins SDA on A4(analog) and SCL on A5, but I'm not dealing with analog signals.  I'm not sure how to #define these as they are also PC4 and PC5, respectively.

Any input would be great appreciated.

Update - On the Inter-Integrated Circuit (I2C) Protocol page (https://docs.arduino.cc/learn/communication/wire), it implies the defines would look like this:
#define SCL A5        
#define SDA A4

Am I interpreting this correctly?

Thanks,
Dave

**Comment by sfe-SparkFro** [comment] 2023-11-30 16:35
Hi there, sorry to hear you're having trouble!

The `SDA` and `SCL` pins should already be `#define`'d for you when you select your board in the Arduino IDE, then the Wire library then uses those `#defined`'d pins, so no need to do that yourself. I'd suggest trying an I2C scan to see whether any devices on the bus send an ACK; if not, it could also be a wiring issue, so make sure your SDA and SCL pins aren't flipped.

This issue does not appear to be an issue with this library, so I'm going to close it for now. If you're in need of further assistance, I'd suggest asking on the [SparkFun forum](https://forum.sparkfun.com/), as that's a better place for more general help like this. If you do believe there's truly an issue with this library, please re-open this issue with details about what exactly the problem is.

Hope this helps!

**Closed by sfe-SparkFro** 2023-11-30 16:35 UTC
